sudo: required
os: linux
jdk: openjdk11
node_js: 9

before_install:
  - curl -s http://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install gradle 5.3

before_script:
  - npm install -g grunt-cli

script:
- gradle build
- cd user-interface/ && npm install --save-dev && grunt qunit
